import type { PrReview, MergeRecommendation, RiskLevel } from "./types";

/**
 * PR review rendering — the automated comment posted on a pull request, plus
 * JSON (for tooling) and a self-contained HTML artifact. Sections mirror the
 * spec: Summary · Score delta · New failures · Risks · Recommendation.
 *
 * Pure string formatting; the CLI/GitHub layers decide where the output goes.
 */

export type PrReportFormat = "markdown" | "json" | "html";

const REC_LABEL: Record<MergeRecommendation, string> = {
  approve: "✅ Approve",
  warn: "⚠️ Review recommended",
  block: "⛔ Block merge",
};
const RISK_BADGE: Record<RiskLevel, string> = {
  low: "🟢 Low",
  medium: "🟡 Medium",
  high: "🟠 High",
  critical: "🔴 Critical",
};

function signed(n: number): string {
  return `${n >= 0 ? "+" : ""}${n}`;
}

/** The headline line, e.g. `Score: 92 → 78 (-14)`. */
export function scoreLine(review: PrReview): string {
  return `Score: ${review.base.score} → ${review.head.score} (${signed(review.scoreDelta)})`;
}

export function renderPrMarkdown(review: PrReview): string {
  const L: string[] = [];
  const { delta, risk, decision, blastRadius } = review;

  L.push("## 📦 Package Workbench Report", "");
  L.push(
    `**${scoreLine(review)}** · Risk: ${RISK_BADGE[risk.level]} (${risk.score}/100) · **${REC_LABEL[decision.recommendation]}**`,
    "",
  );

  // Summary
  const newFailures = delta.regressions.filter(
    (r) => r.kind.startsWith("check:") || r.kind === "new_failing_package",
  );
  L.push("### Summary", "");
  L.push(
    `- ${delta.regressions.length} new issue(s), ${delta.improvements.length} resolved`,
  );
  L.push(
    `- Blast radius: **${blastRadius.edited.length}** edited → **${blastRadius.impacted.length}** impacted (${Math.round(blastRadius.coverage * 100)}% of workspace)`,
  );
  L.push("");

  // New failures
  if (delta.regressions.length > 0) {
    L.push("### New Issues", "");
    for (const r of delta.regressions)
      L.push(`- **[${r.severity}]** ${r.detail}`);
    L.push("");
  } else {
    L.push("### New Issues", "", "_None._", "");
  }

  // Changed packages + blast radius
  if (review.changed.length > 0) {
    L.push(
      "### Impacted Packages",
      "",
      "| Package | Reason | Dependents | Centrality |",
      "| --- | --- | ---: | ---: |",
    );
    for (const c of review.changed.slice(0, 15)) {
      L.push(
        `| ${c.name} | ${c.reason} | ${c.dependents} | ${c.centrality.toFixed(2)} |`,
      );
    }
    if (review.changed.length > 15)
      L.push(`| … | ${review.changed.length - 15} more | | |`);
    L.push("");
  }

  // Risks
  if (risk.factors.length > 0) {
    L.push("### Risk Factors", "");
    for (const f of risk.factors)
      L.push(`- **${f.label}** (+${Math.round(f.points)}): ${f.detail}`);
    L.push("");
  }

  // Improvements
  if (delta.improvements.length > 0) {
    L.push("### Improvements", "");
    for (const imp of delta.improvements) L.push(`- ${imp.detail}`);
    L.push("");
  }

  // Recommendation
  L.push(
    "### Recommendation",
    "",
    `**${REC_LABEL[decision.recommendation]}**`,
    "",
  );
  for (const reason of decision.reasons) L.push(`- ${reason}`);
  if (newFailures.length === 0 && decision.recommendation === "approve")
    L.push("- Safe to merge ✅");
  L.push("");
  L.push(`<sub>Generated by Package Workbench · ${review.generatedAt}</sub>`);

  return L.join("\n");
}

interface StructuredPrReport {
  recommendation: MergeRecommendation;
  score: { base: number; head: number; delta: number };
  risk: PrReview["risk"];
  blastRadius: { edited: number; impacted: number; coverage: number };
  newIssues: PrReview["delta"]["regressions"];
  improvements: PrReview["delta"]["improvements"];
  changed: PrReview["changed"];
  decision: PrReview["decision"];
  generatedAt: string;
}

function structured(review: PrReview): StructuredPrReport {
  return {
    recommendation: review.decision.recommendation,
    score: {
      base: review.base.score,
      head: review.head.score,
      delta: review.scoreDelta,
    },
    risk: review.risk,
    blastRadius: {
      edited: review.blastRadius.edited.length,
      impacted: review.blastRadius.impacted.length,
      coverage: review.blastRadius.coverage,
    },
    newIssues: review.delta.regressions,
    improvements: review.delta.improvements,
    changed: review.changed,
    decision: review.decision,
    generatedAt: review.generatedAt,
  };
}

function escapeHtml(s: string): string {
  return s.replace(
    /[&<>]/g,
    (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;" })[c]!,
  );
}

function renderPrHtml(review: PrReview): string {
  const body = escapeHtml(renderPrMarkdown(review));
  const color =
    review.decision.recommendation === "block"
      ? "#dc2626"
      : review.decision.recommendation === "warn"
        ? "#d97706"
        : "#1f9d55";
  return `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><title>Package Workbench PR Review</title>
<style>
  body { font: 14px/1.6 -apple-system, Segoe UI, Roboto, sans-serif; max-width: 860px; margin: 40px auto; padding: 0 20px; color: #111827; }
  pre { white-space: pre-wrap; }
  .badge { display:inline-block; padding:2px 12px; border-radius:999px; color:#fff; font-weight:700; background:${color}; }
</style></head>
<body>
<h1>Package Workbench — PR Review <span class="badge">${escapeHtml(review.decision.recommendation.toUpperCase())}</span></h1>
<p>${escapeHtml(scoreLine(review))}</p>
<pre>${body}</pre>
</body></html>`;
}

/** Render a PR review in the requested format. */
export function renderPrReview(
  review: PrReview,
  format: PrReportFormat,
): string {
  if (format === "json") return JSON.stringify(structured(review), null, 2);
  if (format === "html") return renderPrHtml(review);
  return renderPrMarkdown(review);
}
